### PR TITLE
Add Big Bird (SA-10 SR) to Mk 50 seeker

### PR DESCRIPTION
**Pull request by OfficialDSplayer**
- Changed latest patch date (and wording to better indicate when the data was accurate)
- Checked and added BB to Mk 50 seeker (under SA-10)

### CODE REVIEW

**Comment by AlphabetGhost** [comment]
tried build a pdf version with ur new shrike.md, seems format completely broken with too many table.

**Comment by OfficialDSplayer** [comment]
> tried build a pdf version with ur new shrike.md, seems format completely broken with too many table.

Seems like this is an issue that is seen with other wide tables in the manual such as the stores table or the telelight panel.

**Review by Zabuzard — APPROVED** [review]

**Comment by Zabuzard** [comment]
Im not a fan of exposing the DCS version to the reader like that, but I understand the intention.

Also an option would be to just keep it as dev-comment `<!-- Checked for DCS Version ... -->`, then it is only visible to editors 🤷

**Comment by OfficialDSplayer** [comment]
> Im not a fan of exposing the DCS version to the reader like that, but I understand the intention.
> 
> Also an option would be to just keep it as dev-comment `<!-- Checked for DCS Version ... -->`, then it is only visible to editors 🤷

Yeah not completely a fan of it either but hopefully when the Shrike isn't as "volatile" in how it tracks targets, it'll be okay to remove it since the reader won't have to worry about the info being wrong or out of date.

**Comment by AlphabetGhost** [comment]
> > tried build a pdf version with ur new shrike.md, seems format completely broken with too many table.
> 
> Seems like this is an issue that is seen with other wide tables in the manual such as the stores table or the telelight panel.

have no issues before i introduce new shrike.md, i have only update shrike in last few days, have no idea why it broken 
pdf

**Pull request merged**
