### PR TITLE
Missing external power connect step in startup checklist

### PR DESCRIPTION
**Pull request by fisadev**
Had to renumber the rest of the steps, sorry!

### CODE REVIEW

**Comment by Zabuzard** [comment]
Thanks for your contribution! @Cat107 can you have a look at this? I believe I recall we made this deliberately to support battery startups and having the external power instead in one of the earlier checklists, no?

**Comment by Cat107** [comment]
@fisadev Connecting the external power is the **step 21** of our **Before Interior Inspection (Pilot)**. In the real manual this steps is about only checking if it's on because as far as I remember it was frequently connected even before crew entered the jet.

**Comment by fisadev** [comment]
@Cat107 Oh! That makes sense, sorry then!

Do you think it would make sense to add a small clarification before the steps to remind people to do it, as (AFAIK) it's the only thing that one should "do" that isn't on the startup checklist? I imagine most people just skip the inspection list.

Something like: "If you skipped the before inspection, remember to connect the ground power before doing the start up".

**Comment by Cat107** [comment]
Yeah @fisadev I guess we can consider that, but also keep in mind that the ground power isn't technically mandatory. You can start the engines using the battery power but irl the battery starts were almost never done as you can't do the full preflight checks and INS pre-heating then.

**Comment by fisadev** [comment]
@Cat107 I updated the pull request with that idea instead. Feel free to close it if you don't think it should be added, no worries! Just trying to help :)

**Comment by fisadev** [comment]
@Cat107 it's great! :)

**Review by Zabuzard — APPROVED** [review]

**Comment by Zabuzard** [comment]
@fisadev Awesome stuff, thanks for your contribution! :)

**Comment by fisadev** [comment]
Thanks to you for the awesome work you've done with the module and manual :heart:

**Pull request merged**
